admin_password: ENC[AES256_GCM,data:RaGQ/HOGZbZJQXxdaD0=,iv:zQ78L84s0FXG0mWVMZRjGlRTY96q0D/PDd+lFQaWsjk=,tag:fU3INeECMnhLH8lIK0eZJQ==,type:str]
jwt_secret: ENC[AES256_GCM,data:QKdFsr1J7YVUhhs8PNu4wD3kxuQ2DycAZotLV8sjmI8=,iv:KtV0EyC6Yqwg8Z101hsdyV8sb0GFzycnj3OWPw9MLBY=,tag:cfeqKmhrfFYmptwMJn3+DA==,type:str]
sops:
    lastmodified: "2026-06-30T22:51:41Z"
    mac: ENC[AES256_GCM,data:74UxccjQ9GXwyCGA2zCTjIcI/5AVEUwhNJcskIB6OAoVR4nU8Yz8xxe3RiDlMv6C/H4raTGSAvqOr/3BVjORbIc+HZA/p7cVr6l+/A4am+zLh2gyD1Kfeh4qhPDsDzdHe3C2wF1k6WrXrfwdNZd5dDSZ/+O/+tBUlWcBSR3W1ig=,iv:NPLo6VTvBLZrV3+Xbo7SCRegCwIGT7Teb8iie60nhTU=,tag:CzzF1GH3DguLh7oL83isnQ==,type:str]
    pgp:
        - created_at: "2026-06-30T23:14:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ibUQCU9alXARAAo0dUvcXHQXG5Nv66MalTcIBok5JgdDpLKL9LsjWUnFup
            KykXInyHiSvzosBGbNflKEEQppoa5PKVx0RqE0WS/O1hQHgASUQ29hxwSIzIwv2u
            4pUdSs9/2U5hoy0sOX6J2m1D0qQtfp0IsBDHNFN/ufY/hG8Ipb18YCdG93G9s8UL
            122y8xvSaWwjrZklsCKdc5wJmOmcBKBki/GO/wj56rClKoTqY7sNxlUllLKqmlHo
            pyWPygAIYdj/AEXMTRF6eUXQeaF/mmJVudqvOlYD23byMmOQN/jUofgx+nhhlu+C
            +jdnYPbFUhGFASM/qZrx2l5kU1QGVJKnoFGLv8U/HFZp/8cLaSG7YkIgcKrC1a4q
            O7EVzLnkPRZ+zjDv3NViF6/NtnB8G8sCbgO8a7utf0nqowD3kKWjWAaEWJ7lOrez
            qvbbI7BPdFAyKPbwQCPQy0n4zqIyv3dFoonsa/PnsepbKGSuFjMWrHw8PU/V255J
            W2iR6ooi6JiZqo+ue2DUrtw+Y6odI51twOq07gDqWudFYORyzjyOcqH2PD3X2ry7
            Ctfb9kMZGMM0nbsv8ZqGwXyrTr62v4qVh6gvd/JJBupSkLK5BTzyaErAMkemLr+8
            TGOel/9iFch6pAU8SWaUuKieMtB1RDABIyxoPQp5s2EBZdOO/jNZHobKxaaMK3bU
            aAEJAhArT4hjNoZODkAkzK7RtQyMpegs5xNaWzQXh2Lj8jbTdOtz4UuOsfqMJ7K4
            mBiV31nSjXfV6krbjAralQnQW53mHBcVCNuWbl8kIDuBrY0VzSBjBF6sAnP/Xz6t
            a5Jx1YaGd3OG
            =6Miu
            -----END PGP MESSAGE-----
          fp: CBB627B1EF016B88EF9E1EAC28B756F87AA868BC
        - created_at: "2026-06-30T23:14:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dx3Taj5silv8SAQdAB2fccCJAPaPKAG1rD7SqOWxN49FgAW5EYnAbDJdH7Fgw
            E9gJF5Rkasl0arCQhxatBrt3Ty2+z2JMWijxbUnAx15EioB0AE4X/xkTl/mb+Vd2
            1GgBCQIQUGtzKAKOMhixvBNUlOvEwToUYHmE9JazKNe7SSXpSV2cH50lJNP6dqIS
            Qcwp6OCejhaWa7KxZtSq03zjzXC1KDzZDXILMpQS9NAilCPNzTskkp8LH2hQhHkO
            cQSpXad87YGuvg==
            =XHqG
            -----END PGP MESSAGE-----
          fp: 79A2BF13FBBC1680B3632355527A30F2116B415C
    unencrypted_suffix: _unencrypted
    version: 3.12.2
