// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Candidate struct {
	ID        int64
	Username  string
	WheelID   int64
	CreatorID string
	CreatedAt sql.NullTime
}

type Wheel struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	WinnerID    sql.NullInt64
}
