// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const addCandidateToWheel = `-- name: AddCandidateToWheel :exec
INSERT INTO candidates (username, wheel_id, creator_id) VALUES (?, ?, ?)
`

type AddCandidateToWheelParams struct {
	Username  string
	WheelID   int64
	CreatorID string
}

func (q *Queries) AddCandidateToWheel(ctx context.Context, arg AddCandidateToWheelParams) error {
	_, err := q.db.ExecContext(ctx, addCandidateToWheel, arg.Username, arg.WheelID, arg.CreatorID)
	return err
}

const getCandidateByCreatorIdAndWheelId = `-- name: GetCandidateByCreatorIdAndWheelId :one
SELECT id, username, wheel_id, creator_id, created_at FROM candidates WHERE creator_id = ? AND wheel_id = ?
`

type GetCandidateByCreatorIdAndWheelIdParams struct {
	CreatorID string
	WheelID   int64
}

func (q *Queries) GetCandidateByCreatorIdAndWheelId(ctx context.Context, arg GetCandidateByCreatorIdAndWheelIdParams) (Candidate, error) {
	row := q.db.QueryRowContext(ctx, getCandidateByCreatorIdAndWheelId, arg.CreatorID, arg.WheelID)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WheelID,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getCandidateBySessionIdAndWheelId = `-- name: GetCandidateBySessionIdAndWheelId :one
SELECT id, username, wheel_id, creator_id, created_at FROM candidates WHERE creator_id = ? AND wheel_id = ?
`

type GetCandidateBySessionIdAndWheelIdParams struct {
	CreatorID string
	WheelID   int64
}

func (q *Queries) GetCandidateBySessionIdAndWheelId(ctx context.Context, arg GetCandidateBySessionIdAndWheelIdParams) (Candidate, error) {
	row := q.db.QueryRowContext(ctx, getCandidateBySessionIdAndWheelId, arg.CreatorID, arg.WheelID)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WheelID,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getDuplicateCandidatesForWheel = `-- name: GetDuplicateCandidatesForWheel :one
SELECT id, username, wheel_id, creator_id, created_at FROM candidates WHERE wheel_id = ? AND (username = ? OR creator_id = ?)
`

type GetDuplicateCandidatesForWheelParams struct {
	WheelID   int64
	Username  string
	CreatorID string
}

func (q *Queries) GetDuplicateCandidatesForWheel(ctx context.Context, arg GetDuplicateCandidatesForWheelParams) (Candidate, error) {
	row := q.db.QueryRowContext(ctx, getDuplicateCandidatesForWheel, arg.WheelID, arg.Username, arg.CreatorID)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WheelID,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getWheelByID = `-- name: GetWheelByID :one
SELECT id, name, description, created_at, winner_id FROM wheels WHERE id = ?
`

func (q *Queries) GetWheelByID(ctx context.Context, id int64) (Wheel, error) {
	row := q.db.QueryRowContext(ctx, getWheelByID, id)
	var i Wheel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.WinnerID,
	)
	return i, err
}

const listCandidatesByWheel = `-- name: ListCandidatesByWheel :many
SELECT id, username, wheel_id, creator_id, created_at FROM candidates WHERE wheel_id = ?
`

func (q *Queries) ListCandidatesByWheel(ctx context.Context, wheelID int64) ([]Candidate, error) {
	rows, err := q.db.QueryContext(ctx, listCandidatesByWheel, wheelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candidate
	for rows.Next() {
		var i Candidate
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.WheelID,
			&i.CreatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWheels = `-- name: ListWheels :many
SELECT id, name, description, created_at, winner_id FROM wheels
`

func (q *Queries) ListWheels(ctx context.Context) ([]Wheel, error) {
	rows, err := q.db.QueryContext(ctx, listWheels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wheel
	for rows.Next() {
		var i Wheel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.WinnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
