// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countWheels = `-- name: CountWheels :one
SELECT COUNT(*) FROM wheels
`

func (q *Queries) CountWheels(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWheels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCandidate = `-- name: CreateCandidate :exec
INSERT INTO candidates (username, wheel_id, creator_id) VALUES (?, ?, ?)
`

type CreateCandidateParams struct {
	Username  string
	WheelID   int64
	CreatorID string
}

func (q *Queries) CreateCandidate(ctx context.Context, arg CreateCandidateParams) error {
	_, err := q.db.ExecContext(ctx, createCandidate, arg.Username, arg.WheelID, arg.CreatorID)
	return err
}

const createWheel = `-- name: CreateWheel :execlastid
INSERT INTO wheels (name, description) VALUES (?, ?)
`

type CreateWheelParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateWheel(ctx context.Context, arg CreateWheelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createWheel, arg.Name, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const declareWinnerForWheel = `-- name: DeclareWinnerForWheel :exec
UPDATE wheels SET winner_id = ?, status = 'winner_declared' WHERE id = ?
`

type DeclareWinnerForWheelParams struct {
	WinnerID sql.NullInt64
	ID       int64
}

func (q *Queries) DeclareWinnerForWheel(ctx context.Context, arg DeclareWinnerForWheelParams) error {
	_, err := q.db.ExecContext(ctx, declareWinnerForWheel, arg.WinnerID, arg.ID)
	return err
}

const deleteCandidateByID = `-- name: DeleteCandidateByID :exec
DELETE FROM candidates WHERE id = ? AND wheel_id = ?
`

type DeleteCandidateByIDParams struct {
	ID      int64
	WheelID int64
}

func (q *Queries) DeleteCandidateByID(ctx context.Context, arg DeleteCandidateByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteCandidateByID, arg.ID, arg.WheelID)
	return err
}

const deleteWheelByID = `-- name: DeleteWheelByID :exec
DELETE FROM wheels WHERE id = ?
`

func (q *Queries) DeleteWheelByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWheelByID, id)
	return err
}

const getCandidateByCreatorIDAndWheelID = `-- name: GetCandidateByCreatorIDAndWheelID :one
SELECT id, username, wheel_id, creator_id, created_at FROM candidates WHERE creator_id = ? AND wheel_id = ?
`

type GetCandidateByCreatorIDAndWheelIDParams struct {
	CreatorID string
	WheelID   int64
}

func (q *Queries) GetCandidateByCreatorIDAndWheelID(ctx context.Context, arg GetCandidateByCreatorIDAndWheelIDParams) (Candidate, error) {
	row := q.db.QueryRowContext(ctx, getCandidateByCreatorIDAndWheelID, arg.CreatorID, arg.WheelID)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WheelID,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getCandidateByID = `-- name: GetCandidateByID :one
SELECT id, username, wheel_id, creator_id, created_at FROM candidates WHERE id = ? AND wheel_id = ?
`

type GetCandidateByIDParams struct {
	ID      int64
	WheelID int64
}

func (q *Queries) GetCandidateByID(ctx context.Context, arg GetCandidateByIDParams) (Candidate, error) {
	row := q.db.QueryRowContext(ctx, getCandidateByID, arg.ID, arg.WheelID)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WheelID,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getCandidateBySessionIDAndWheelID = `-- name: GetCandidateBySessionIDAndWheelID :one
SELECT id, username, wheel_id, creator_id, created_at FROM candidates WHERE creator_id = ? AND wheel_id = ?
`

type GetCandidateBySessionIDAndWheelIDParams struct {
	CreatorID string
	WheelID   int64
}

func (q *Queries) GetCandidateBySessionIDAndWheelID(ctx context.Context, arg GetCandidateBySessionIDAndWheelIDParams) (Candidate, error) {
	row := q.db.QueryRowContext(ctx, getCandidateBySessionIDAndWheelID, arg.CreatorID, arg.WheelID)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WheelID,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getDuplicateCandidatesForWheel = `-- name: GetDuplicateCandidatesForWheel :one
SELECT id, username, wheel_id, creator_id, created_at FROM candidates WHERE wheel_id = ? AND (username = ? OR creator_id = ?)
`

type GetDuplicateCandidatesForWheelParams struct {
	WheelID   int64
	Username  string
	CreatorID string
}

func (q *Queries) GetDuplicateCandidatesForWheel(ctx context.Context, arg GetDuplicateCandidatesForWheelParams) (Candidate, error) {
	row := q.db.QueryRowContext(ctx, getDuplicateCandidatesForWheel, arg.WheelID, arg.Username, arg.CreatorID)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.WheelID,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getWheelByID = `-- name: GetWheelByID :one
SELECT id, name, description, status, created_at, winner_id FROM wheels WHERE id = ?
`

func (q *Queries) GetWheelByID(ctx context.Context, id int64) (Wheel, error) {
	row := q.db.QueryRowContext(ctx, getWheelByID, id)
	var i Wheel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.WinnerID,
	)
	return i, err
}

const listCandidatesByWheel = `-- name: ListCandidatesByWheel :many
SELECT id, username, wheel_id, creator_id, created_at FROM candidates WHERE wheel_id = ?
`

func (q *Queries) ListCandidatesByWheel(ctx context.Context, wheelID int64) ([]Candidate, error) {
	rows, err := q.db.QueryContext(ctx, listCandidatesByWheel, wheelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candidate
	for rows.Next() {
		var i Candidate
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.WheelID,
			&i.CreatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWheels = `-- name: ListWheels :many
SELECT id, name, description, status, created_at, winner_id FROM wheels
`

func (q *Queries) ListWheels(ctx context.Context) ([]Wheel, error) {
	rows, err := q.db.QueryContext(ctx, listWheels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wheel
	for rows.Next() {
		var i Wheel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.WinnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWheelStatus = `-- name: SetWheelStatus :exec
UPDATE wheels SET status = ? WHERE id = ?
`

type SetWheelStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) SetWheelStatus(ctx context.Context, arg SetWheelStatusParams) error {
	_, err := q.db.ExecContext(ctx, setWheelStatus, arg.Status, arg.ID)
	return err
}
